version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./faiss_index:/app/faiss_index
      - ./db.sqlite:/app/db.sqlite
      - ./.env:/app/.env
      - ./config.yaml:/app/config.yaml
    environment:
      - DATABASE_URL=sqlite:///./db.sqlite
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3